FROM python:3.10.9

COPY ./bot /bot_app

WORKDIR /bot_app
COPY ./requirements.txt /bot_app/
RUN pip install --no-cache-dir -r requirements.txt watchfiles

CMD ["watchfiles", "python app.py", "/bot_app"]


