# Generated by Django 5.2.7 on 2025-10-18 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('user_first_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Skin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, max_length=255, null=True)),
                ('skin_id', models.CharField(max_length=255)),
                ('skin_name', models.CharField(max_length=255)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_checked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('skin_id', 'condition'), name='unique_skin_condition')],
            },
        ),
        migrations.CreateModel(
            name='UserSkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_notified_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('active_track', models.BooleanField(default=False)),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='skinsapp.skin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skinsapp.botuser')),
            ],
            options={
                'unique_together': {('user', 'skin')},
            },
        ),
    ]
