# Generated by Django 5.2.7 on 2025-10-19 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userskin',
            name='active_track',
        ),
        migrations.AddField(
            model_name='userskin',
            name='threshold_value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
