# Generated by Django 5.2.7 on 2025-10-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinsapp', '0002_remove_userskin_active_track_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userskin',
            name='threshold_value',
            field=models.IntegerField(default=0),
        ),
    ]
