# Generated by Django 5.2.7 on 2025-10-21 20:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinsapp', '0003_alter_userskin_threshold_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='last_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='userskin',
            name='last_notified_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='userskin',
            name='threshold_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
