# Generated by Django 5.2.7 on 2025-10-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skinsapp', '0004_alter_skin_last_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='condition',
            field=models.CharField(default='Collections', max_length=255),
        ),
    ]
